### ISSUE TITLE
pix_opencv_contours consistency check error + crash

### ISSUE THREAD

**Issue by fdch** [avilleret/pix_opencv#10] opened 2019-02-28 14:11 UTC
the consistency check error happens when directly printing to console from the second outlet of [pix_opencv_contours]. It may lead to a crash when that happens several times. 

A definite crash `Segmentation fault: 11` occurs when you try to [route contours] out of that inlet.

This crash basically disables the possibility for the actual contour data to be outputted. I would give it try once I get a chance to compile in macos (#9), it seems that https://github.com/avilleret/pix_opencv/blob/4fc0db7b9638b3fc90537b5b2f5e0342bfef3722/src/pix_opencv_contours.cc#L410

should be 
`outlet_anything(m_dataout_middle, gensym("contour"), size, apt);`

**Comment by avilleret** [comment] 2020-09-02 09:59
I disagree since `apt` is kind of iterator, we should pass a pointer to the beginning of the `acounters` array.

I'll check if it is still relevant today with opencv4 upgrade.

**Comment by avilleret** [comment] 2020-09-02 10:01
afaik table output is not crashing in opencv4 branch, could you check on your side with 4fc0db7b ?

thanks

**Comment by avilleret** [comment] 2020-09-07 15:54
so I'm closing it since it seems to work, feel free to reopen with the step to reproduce with the latest commit on opencv4 branch.

**Closed as completed by avilleret** 2020-09-07 15:54 UTC
